# Generated by Django 4.1.5 on 2023-02-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_capaciy_taxi_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxi",
            name="fare",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="taxi",
            name="taxi_number",
            field=models.IntegerField(),
        ),
    ]
