# Generated by Django 4.1.5 on 2023-02-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_taxi_fare_alter_taxi_taxi_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.TextField(max_length=80)),
                ("amount", models.IntegerField(default=0)),
                ("notes", models.TextField(default="")),
            ],
        ),
        migrations.DeleteModel(
            name="Taxi",
        ),
    ]
